import jsPDF from 'jspdf';
import { GeneratedDocument } from '../types';

export const exportToPDF = (doc: GeneratedDocument, schoolName: string = 'SOMA UGANDA', district?: string) => {
  const pdf = new jsPDF({
    unit: 'mm',
    format: 'a4',
  });

  // Header Colors
  const primaryGreen = [27, 67, 50]; // #1B4332

  // --- HEADER SECTION ---
  pdf.setFillColor(primaryGreen[0], primaryGreen[1], primaryGreen[2]);
  pdf.rect(0, 0, 210, 45, 'F');

  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(9);
  pdf.text('REPUBLIC OF UGANDA', 105, 12, { align: 'center' });
  
  pdf.setFontSize(18);
  pdf.setFont('helvetica', 'bold');
  pdf.text(schoolName.toUpperCase(), 105, 24, { align: 'center' });
  
  if (district) {
    pdf.setFontSize(11);
    pdf.setFont('helvetica', 'normal');
    pdf.text(district.toUpperCase() + ' DISTRICT', 105, 32, { align: 'center' });
  }

  pdf.setFontSize(9);
  pdf.setFont('helvetica', 'normal');
  pdf.text('PROFESSIONAL CURRICULUM RESOURCE', 105, district ? 38 : 34, { align: 'center' });

  // --- DOC INFO ---
  pdf.setTextColor(0, 0, 0);
  pdf.setFontSize(12);
  pdf.setFont('helvetica', 'bold');
  pdf.text(doc.title, 15, 50);

  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'normal');
  pdf.text(`Subject: ${doc.subject}`, 15, 58);
  pdf.text(`Class: ${doc.class_level}`, 15, 63);
  pdf.text(`Date: ${new Date(doc.created_at).toLocaleDateString()}`, 195, 58, { align: 'right' });

  // Divider
  pdf.setDrawColor(primaryGreen[0], primaryGreen[1], primaryGreen[2]);
  pdf.setLineWidth(0.5);
  pdf.line(15, 68, 195, 68);

  // --- CONTENT ---
  pdf.setFontSize(11);
  const margin = 15;
  const pageWidth = 210;
  const maxWidth = pageWidth - (margin * 2);
  
  // Basic Markdown-ish stripping for PDF
  const cleanContent = doc.content
    .replace(/#{1,6}\s?/g, '') // Remove headers
    .replace(/\*\*/g, '');      // Remove bold marks

  const lines = pdf.splitTextToSize(cleanContent, maxWidth);
  
  let cursorY = 78;
  const pageHeight = 297;

  lines.forEach((line: string) => {
    if (cursorY > pageHeight - 20) {
      pdf.addPage();
      cursorY = 20;
    }
    pdf.text(line, margin, cursorY);
    cursorY += 6;
  });

  // Footer
  const pageCount = pdf.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    pdf.setPage(i);
    pdf.setFontSize(8);
    pdf.setTextColor(150);
    pdf.text(`Page ${i} of ${pageCount} | Generated by Soma Uganda`, 105, 287, { align: 'center' });
  }

  pdf.save(`${doc.title.replace(/\s+/g, '_')}.pdf`);
};
