import { saveAs } from 'file-saver';
import { asBlob } from 'html-docx-js-typescript';
import { GeneratedDocument } from '../types';

export const exportToWord = async (doc: GeneratedDocument) => {
  const htmlContent = `
    <!DOCTYPE html>
    <html lang="en">
      <head>
        <meta charset="utf-8">
        <title>${doc.title}</title>
        <style>
          body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; line-height: 1.6; color: #333; }
          h1 { color: #1B4332; text-align: center; }
          .header { border-bottom: 2px solid #1B4332; margin-bottom: 20px; padding-bottom: 10px; }
          .meta { font-size: 10pt; color: #666; margin-bottom: 20px; }
          .content { white-space: pre-wrap; }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>${doc.title}</h1>
        </div>
        <div class="meta">
          <strong>Subject:</strong> ${doc.subject} | 
          <strong>Class:</strong> ${doc.class_level} | 
          <strong>Date:</strong> ${new Date(doc.created_at).toLocaleDateString()}
        </div>
        <div class="content">${doc.content}</div>
        <div style="margin-top: 50px; font-size: 8pt; color: #999; text-align: center;">
          Generated by SOMA Uganda — Curriculum Assistant
        </div>
      </body>
    </html>
  `;

  try {
    const blob = await asBlob(htmlContent);
    saveAs(blob as Blob, `${doc.title.replace(/\s+/g, '_')}.docx`);
  } catch (error) {
    console.error('Word export failed:', error);
  }
};
